version: 2
updates:
- package-ecosystem: docker
  directory: "/7.4"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: php
    versions:
    - 8.0.1
    - 8.0.2
- package-ecosystem: docker
  directory: "/7.4-apache"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: php
    versions:
    - 8.0.1.pre.apache
    - 8.0.2.pre.apache
